name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Install libusb
        run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=${{ matrix.goarch }} go build -o dist/digispark-${{ matrix.goarch }} ./cmd/digispark/main.go
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: digispark-${{ matrix.goarch }}
          path: dist/digispark-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/digispark-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
